# C_SRC += $(wildcard common/*.c)
# CPP_SRC += main.cpp
# C_SRC += $(shell find . -type f -name *.c)
# EXTRA_OPT += -fno-lto

# C_SRC += $(wildcard *.c)
C_SRC_DIR += .

include $(TOPDIR)/Makefile.inc
